import React from 'react'
import { List, ListItem, ListItemText } from '@mui/material'

// const hours = 24 later set items to be generated by code instead of hard coding each component

export default function Timeline (props) {
  return (
  // <List style={{ height: '100%', border: '2px solid black', overflow: 'auto' }}>
  // overflow auto gives scroll bar for the react component
      <List style={{ height: '85vh' }}>
    <ListItem >
      <ListItemText primary="Time"/>
    </ListItem>
    {/* lets make a loop for each hour on our timeline */}
    <ListItem >
      <ListItemText>1</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>2</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>3</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>4</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>5</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>6</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>7</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>8</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>9</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>10</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>11</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>12</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>1</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>2</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>3</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>4</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>5</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>6</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>7</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>8</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>9</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>10</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>11</ListItemText>
    </ListItem>
    <ListItem >
      <ListItemText>12</ListItemText>
    </ListItem>
  </List>
  )
}
