# Workflow for testing code and submitting a codecov report

name: Build, Test and Coverage Report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events 
  [push, pull_request]

jobs:
  build:
    #run project on latest ubuntu
    runs-on: ubuntu-latest
    
    environment: test

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    #sets up node for version 16 and 18
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #Installs npm packages
    - name: Install dependencies
      run: npm ci

    - name: ESLint
      uses: sibiraj-s/action-eslint@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,jsx,ts,tsx'
        annotations: true

    - name: Build Project
      run: npm run build --if-preset

    #Runs tests through the test script in package.json
    #should be "jest --coverage"
    - name: Run tests
      run: npm run test
    #Uploads coverage report to CodeCov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
